### ISSUE TITLE
Value encoding option in level instance does not work.

### ISSUE THREAD

**Issue by nikugogoi** [kappa-db/kappa-view#2]
Using `valueEncoding` option while creating `level` instance does not give desired result.

**Comment by fwip** [comment]
I fixed this in a local copy by changing line 9 to:
```javascript
var dataDb = sub(ldb, 'd', {valueEncoding: "json"})
```

There's probably a smarter way to automatically inherit the leveldb's encoding, but I don't know a robust way to do it.

Edit: Oh nevermind, you already figured it out in PR #3.

**Comment by hackergrrl** [comment]
I added an opts param though in 7cd25be that should meet your needs. `3.1.0`
